version: 2
updates:

  # Project Dependencies.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: daily
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  # Project Tools.

  - package-ecosystem: composer
    directory: "/tools/parallel-lint"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  - package-ecosystem: composer
    directory: "/tools/phpcs"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  - package-ecosystem: composer
    directory: "/tools/phpcpd"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  - package-ecosystem: composer
    directory: "/tools/phpmd"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  - package-ecosystem: composer
    directory: "/tools/phpstan"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  - package-ecosystem: composer
    directory: "/tools/phpunit"
    registries: "*"
    schedule:
        interval: daily
        time: "06:30"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"

  # NPM.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "06:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    commit-message:
        prefix: "[Upgraded]"
        prefix-development: "[Upgraded]"
