---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Vatu:    Commit
# Version: 1.0.0
# Author:  Michael Bragg <mike@vatu.co.uk>

name: 'Commit'

on:

  workflow_dispatch:

  pull_request:
    branches:
      - main
      - develop
      - uat

  push:
    branches:
      - main
      - develop
      - uat

concurrency:
  group: ${{ github.workflow }}--${{ github.ref_name || github.head_ref }}
  cancel-in-progress: true

env:
  COMPOSER_ALLOW_SUPERUSER: "1" # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:

  php-parallel-lint:
    name: "PHP Parallel Lint"
    uses: vatu-team/workflows/.github/workflows/php-parallel-lint.yml@1.12.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.3'
    secrets: inherit

  phpcs:
    name: "PHP CodeSniffer"
    needs: php-parallel-lint
    uses: vatu-team/workflows/.github/workflows/php-codesniffer.yml@1.12.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.3'
    secrets: inherit

  phpmnd:
    name: "PHP Magic Number Detector"
    needs: phpcs
    uses: vatu-team/workflows/.github/workflows/php-magic-number-detector.yml@1.12.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.3'
    secrets: inherit

  phpcpd:
    name: "PHP Copy/Paste Detector"
    needs: phpmnd
    uses: vatu-team/workflows/.github/workflows/php-copy-paste-detector.yml@1.12.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.3'
    secrets: inherit

  phpstan:
    name: "PHP Stan"
    needs: phpcpd
    uses: vatu-team/workflows/.github/workflows/php-stan.yml@1.12.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.3'
    secrets: inherit

  notify-failure:
    name: "Notify on failure."
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs:
      - php-parallel-lint
      - phpcs
      - phpmnd
      - phpcpd
      - phpstan
    runs-on: 'self-hosted'
    steps:
      - name: "Failure notification."
        if: ${{ failure() }}
        id: 'slack'
        uses: 'slackapi/slack-github-action@v1.25.0'
        with:
          channel-id: 'updates'
          payload: |
            {
              "text": "${{ github.workflow }} workflow failed for ${{ github.event.repository.name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.workflow }} workflow failed for ${{ github.event.repository.name }}.\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
