# Vatu: Dependabot Auto Merge Slack Notification
# Version: 0.1.0
# Author: Artem Sapegin
# Link: https://blog.sapegin.me/til/misc/automatically-merging-dependabot-security-pull-requests-using-github-actions/

name: "Slack Notifications"

on:
  workflow_run:
    workflows:
      - "Dependabot Auto Merge"
    types:
      - completed

jobs:
  slackNotification:
      name: Dependabot Auto Merge
      runs-on: ubuntu-latest

      # Only run if the previous workflow was successful.
      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON: https://avatars.githubusercontent.com/in/29110?s=88&v=4
          SLACK_MESSAGE: ${GITHUB_REF#refs/heads/}
          SLACK_TITLE: "Dependabot Auto Merge"
          SLACK_USERNAME: "Dependabot"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
