# Vatu: Dependabot: Auto Merge
# Version: 0.1.0
# Author: Artem Sapegin
# Link: https://blog.sapegin.me/til/misc/automatically-merging-dependabot-security-pull-requests-using-github-actions/

name: "Dependabot"

on:
  workflow_run:
    workflows:
     - "Run QA Sniffs"
    types:
      - completed
    # pull_request_target:
    #   types:
    #     - opened
    #     - synchronize

jobs:

# Dependabot Auto Merge.
#
# Performs the following steps:
# - Show when worflow is run.
  on-success:
    name: "Auto Merge"
    runs-on: ubuntu-latest

    # Only run if the previous workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Only run if the creator is Dependabot.
    #if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/github-script@v4

        with:
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'rebase'
            })
