# Vatu: Dependabot Auto Merge Slack Notification
# Version: 0.1.1

name: "Slack Notifications"

# Only run this workflow after the `dependabot` workflow is run.

on:
  workflow_run:
    workflows:
      - dependabot
    types:
      - completed

jobs:

  # Slack Notification on Dependabot Merge
  #
  # Performs the following steps:
  # - Check if `Dependabot` workflow was successful.
  # - Build notification message body.
  # - Post Slack notification message

  slackNotification:
      name: Dependabot Auto Merge
      runs-on: ubuntu-latest

      # Only run if the previous workflow was successful.
      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      steps:

      - name: "Build notificaiton nessage body."
        run: echo "slack_message=$( printf '%s on %s repository.' "${ github.event.pull_request.title }" "${GITHUB_REPOSITORY}" )" >> $GITHUB_ENV

      - name: "Temp"
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event }}

      - name: "Post Slack notification message"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/in/29110?s=88&v=4
          SLACK_MESSAGE: ${{ env.slack_message }}
          SLACK_TITLE: "Dependabot Auto Merge"
          SLACK_USERNAME: "Dependabot"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
