# Vatu:   Dependabot Auto Merge
# Version 1.0.0-beta
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Dependabot Auto Merge"

on:
  workflow_run:
    workflows: ["Static Analysis"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}--${{ github.ref_name || github.head_ref }}
  cancel-in-progress: true

jobs:

  auto-merge:

    # Conditions for running workflow (project specific).
    if: >
      github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.conclusion == 'success'

    name: "Auto Merge"
    uses: vatu-team/workflows/.github/workflows/auto-merge-pr.yml@1.0.0-beta.7
    with:
      runs-on: 'self-hosted'
    secrets:
      BOT_ID: ${{ secrets.VATU_BOT_ID }}
      BOT_KEY: ${{ secrets.VATU_BOT_KEY }}
