# Vatu Production Deploy
# Version: 0.1.0

name: Deploy to Production

on:
  push:
    branches:
      - 'feature/*'
      - '!*-built'
  workflow_dispatch:

jobs:
  # Deploy code to production.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information.
  # - Install Composer dependencies with no dev option.
  # - Install NPM dependencies.
  # - Built theme.
  # - Remove `.gitignore` files.
  # - Remove deployment ignore files.
  # - Commit to `main-built`

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: "Checks out the repository."
        uses: "actions/checkout@v2"
      - name: Sets up PHP with Composer.
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Logs debug information.
        run: |
          php --version
          composer --version
      - name: Install Composer dependencies.
        run: composer install --no-dev --no-interaction --prefer-dist
      - name: "Making the build directory"
        run: |
          git init ${GITHUB_WORKSPACE}/build/
          cd ${GITHUB_WORKSPACE}/build/
          git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          git remote -v
      - name: "Rsync files to build directory"
        run: rsync --delete -a "${GITHUB_WORKSPACE}/" "${GITHUB_WORKSPACE}/build" --exclude='.git/,build/'
      - name: "Remove `.gitignore` file"
        run: rm .gitignore
      - name: "Setup deploy ignore files."
        run: mv .deployignore .gitignore
      - name: "List directory"
        run: ls -a ${GITHUB_WORKSPACE}/build/
