# Vatu Health Check
# Version: 0.2.0

name: Health check

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  # Test deployied code is working as expected.
  #
  # Performs the following steps:
  # - Get current branch name.
  # - Checks out the repository.
  # - Setup NodeJS.
  # - Logs debug information.
  # - Install Node Modules.
  # - Run Health Check tests.

  e2e:
    name: "Health Check"
    runs-on: self-hosted

    # Only run if previous workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: "Get current branch name."
        run : |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: "Checks out the repository."
        uses: actions/checkout@v3.0.2

      - name: "Setup NodeJS."
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VATU_GITHUB_TOKEN }}

      - name: "Logs debug information."
        run: |
          node --version
          npm --version

      - name: "Install Node Modules."
        run: |
          git config --global --add url."https://${{ secrets.VATU_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url.https://${{ secrets.VATU_GITHUB_TOKEN }}:x-oauth-basic@github.com/.insteadOf ssh://git@github.com/
          git config --global url.https://${{ secrets.VATU_GITHUB_TOKEN }}:x-oauth-basic@github.com/.insteadOf git://github.com/
          npm install

      - name: "Run Health Check tests."
        run: npx percy exec -- cypress run --config-file tests/cypress.json --config baseUrl=https://demo.vatu.dev --spec tests/cypress/integration/00-setup/00-health-check.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
