# Vatu Health Check
# Version: 0.1.0

name: Health check

on:
  workflow_run:
    workflows: ["Deploy Build"]
    types:
      - completed

jobs:
  # Test deployied code is working as expected.
  #
  # Performs the following steps:
  # - Get current branch name.
  # - Checks out the repository.
  # - Setup NodeJS.
  # - Install NodeJS dependencies.
  # - Run Health Check tests.

  e2e:
    name: "Health Check"
    runs-on: ubuntu-latest

    # Only run if previous workflow was successful.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: "Get current branch name."
        run : |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: "Checks out the repository."
        uses: actions/checkout@v2

      - name: "Setup NodeJS."
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install NodeJS dependencies."
        run: npm install

      - name: "Run Health Check tests."
        run: npx percy exec -- cypress run --config baseUrl=https://demo.vatu.dev --spec cypress/integration/00-setup/00-health-check.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
