---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Vatu:    Static Analysis
# Version: 1.0.0
# Author:  Michael Bragg <mike@vatu.co.uk>

name: 'Static Analysis'

on:

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.ref_name || github.head_ref }}
  cancel-in-progress: true

jobs:

  php-parallel-lint:
    name: "PHP Parallel Lint"
    uses: vatu-team/workflows/.github/workflows/php-parallel-lint.yml@1.10.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.2'
    secrets: inherit

  phpcs:
    name: "PHP CodeSniffer"
    needs: php-parallel-lint
    uses: vatu-team/workflows/.github/workflows/php-codesniffer.yml@1.10.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.2'
    secrets: inherit

  phpmnd:
    name: "PHP Magic Number Detector"
    needs: phpcs
    uses: vatu-team/workflows/.github/workflows/php-magic-number-detector.yml@1.10.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.2'
    secrets: inherit

  phpcpd:
    name: "PHP Copy/Paste Detector"
    needs: phpmnd
    uses: vatu-team/workflows/.github/workflows/php-copy-paste-detector.yml@1.10.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.2'
    secrets: inherit

  phpstan:
    name: "PHP Stan"
    needs: phpcpd
    uses: vatu-team/workflows/.github/workflows/php-stan.yml@1.10.0
    with:
      runs-on: 'self-hosted'
      version-php: '8.2'
    secrets: inherit
