name: tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  phive:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Cache tools installed with PHIVE"
        uses: "actions/cache@v2.1.2"
        with:
          path: "$HOME/.phive"
          key: "${{ runner.os }}-phive-${{ hashFiles('.phive/phars.xml') }}"
          restore-keys: "${{ runner.os }}-phive-"
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phive
      - name: Debug PHIVE
        run: phive --version
      - name: Install PHIVE packages
        run: phive install --trust-gpg-keys "0F9684B8B16B7AB0,4AA394086372C20A,31C7E470E2138192,CBB3D576F2A0946F"
      - name: Install WordPress Coding Standards
        run: git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git --branch 2.3.0 ./tools/wpcs
      - name: Set PHPCS config installed paths
        run: ./tools/phpcs --config-set installed_paths ./tools/wpcs
      - name: Test Coding Standards
        run: php ./tools/phpcs -i
